birthyear = input("Masukkan tahun lahir: ")
tahunsekarang = input("Masukkan tahun sekarang: ")
age = int(tahunsekarang) - int(birthyear)
print("kamu lahir tahun", birthyear)
print("umur kamu", age, "tahun")